#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

pacman-key --init
pacman-key --populate archlinux
pacman -Syu sslh nano --noconfirm

cp /tmp/contents/static/sslh.conf /etc/sslh.cfg

rm -rf /var/cache/* /tmp/* /var/tmp/*

